version: '3.4'

services:
  shriek.cms.ui.web:
    image: ${DOCKER_REGISTRY}shriekcmsuiweb
    build:
      context: .
      dockerfile: src/Shriek.CMS.UI.Web/Dockerfile

  shriek.cms.application.services:
    image: ${DOCKER_REGISTRY}shriekcmsapplicationservices
    build:
      context: .
      dockerfile: src/Shriek.CMS.Application.Services/Dockerfile
  shriek.cms.ui.admin:
    image: ${DOCKER_REGISTRY}shriekcmsuiadmin
    build:
      context: .
      dockerfile: src/Shriek.CMS.UI.Admin/Dockerfile

